name: Trading Bot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  run-trading-bot:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Execute trading bot
        run: python main.py
